Update release-nuget.yml

diff --git a/.github/workflows/release-nuget.yml b/.github/workflows/release-nuget.yml
--- a/.github/workflows/release-nuget.yml
+++ b/.github/workflows/release-nuget.yml
@@ -3,36 +3,37 @@ name: Create a (Pre)release on NuGet
 on:
   push:
     tags:
-    - "[0-9]+.[0-9]+.[0-9]+"
-    - "[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"
+      - "[0-9]+.[0-9]+.[0-9]+"
+      - "[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"
+
 jobs:
   release-nuget:
-  
     runs-on: windows-latest
 
     steps:
       - uses: actions/checkout@v3
+
       - name: Verify commit exists in origin/main
         run: |
           git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
-          git branch --remote --contains | grep origin/main
+          if !(git branch --remote --contains | findstr origin/main) {
+            echo "Error: Tag is not in main branch!" 
+            exit 1
+          }
 
       - name: Get version information from tag
         id: get_version
         run: |
-          $version="${{github.ref_name}}".TrimStart("v")
-          "version-without-v=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
+          echo "version=${{ github.ref_name }}" | Out-File -FilePath $env:GITHUB_ENV -Append
 
       - name: Restore dependencies
         run: dotnet restore samples\DemoApp.csproj
 
       - name: Build
-        run: dotnet build src\MAUIWifiManager\MauiWifiManager.csproj -c Release /p:Version=${{ steps.get_version.outputs.version-without-v }}
+        run: dotnet build src\MAUIWifiManager\MauiWifiManager.csproj -c Release /p:Version=${{ env.version }}
 
       - name: Pack
-        run: dotnet pack src\MAUIWifiManager\MauiWifiManager.csproj -c Release /p:Version=${{ steps.get_version.outputs.version-without-v }} --no-build --output .
-        
+        run: dotnet pack src\MAUIWifiManager\MauiWifiManager.csproj -c Release /p:Version=${{ env.version }} --no-build --output .
+
       - name: Push
-        run: dotnet nuget push WifiManager.Maui.${{ steps.get_version.outputs.version-without-v }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.NUGET_API_KEY }}
+        run: dotnet nuget push "*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
